//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dairy
    {
        public int DairyId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<System.TimeSpan> DuringTime { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string Description { get; set; }
        public Nullable<int> TypeMeeting { get; set; }
        public int UserId { get; set; }
    
        public virtual Rooms Rooms { get; set; }
        public virtual TypeMeeting TypeMeeting1 { get; set; }
        public virtual users users { get; set; }
    }
}
