//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KupaToProf
    {
        public string KupaId { get; set; }
        public int ProfId { get; set; }
    
        public virtual KupaToProf KupaToProf1 { get; set; }
        public virtual KupaToProf KupaToProf2 { get; set; }
    }
}
