//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opinion
    {
        public int OpinionId { get; set; }
        public Nullable<int> ProfPersonid { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Mark { get; set; }
    }
}
