//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professions()
        {
            this.Opinion = new HashSet<Opinion>();
            this.Reference = new HashSet<Reference>();
            this.Reference1 = new HashSet<Reference>();
            this.Kupot1 = new HashSet<Kupot1>();
        }
    
        public int ProfId { get; set; }
        public string ProfName { get; set; }
        public int Type { get; set; }
        public string Tel { get; set; }
        public string AddTel { get; set; }
        public string Email { get; set; }
        public string PrivateAddres { get; set; }
        public string ClinicAddres { get; set; }
        public Nullable<int> Subdomain { get; set; }
        public string PrivateOpinion { get; set; }
        public string IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Opinion> Opinion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> Reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> Reference1 { get; set; }
        public virtual Subdomain Subdomain1 { get; set; }
        public virtual typeProfessions typeProfessions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kupot1> Kupot1 { get; set; }
    }
}
